
# ── Countries ────────────────────────────────────────────────────────────────

COUNTRIES: list[str] = [
    "Nigeria",
    "United States",
    "United Kingdom",
    "Kenya",
    "Ghana",
    "South Africa",
    "Canada",
    "India",
    "United Arab Emirates",
    "Germany",
    "Egypt",
    "Rwanda",
    "Ethiopia",
    "Tanzania",
    "Senegal",
    "Côte d'Ivoire",
    "France",
    "Singapore",
    "Australia",
    "Brazil",
]

# ── Regions per country ───────────────────────────────────────────────────────

REGIONS: dict[str, list[str]] = {
    "Nigeria": [
        "Lagos",
        "Abuja (FCT)",
        "Kano",
        "Rivers (Port Harcourt)",
        "Ogun",
        "Oyo (Ibadan)",
        "Enugu",
        "Delta",
        "Anambra",
        "Kaduna",
    ],
    "United States": [
        "California",
        "New York",
        "Texas",
        "Florida",
        "Illinois",
        "Georgia",
        "Massachusetts",
        "Washington",
        "Virginia",
        "North Carolina",
    ],
    "United Kingdom": [
        "London",
        "Manchester",
        "Birmingham",
        "Edinburgh",
        "Bristol",
        "Leeds",
        "Liverpool",
        "Cardiff",
        "Belfast",
        "Sheffield",
    ],
    "Kenya": [
        "Nairobi",
        "Mombasa",
        "Kisumu",
        "Nakuru",
        "Eldoret",
        "Nyeri",
        "Machakos",
        "Thika",
        "Malindi",
        "Garissa",
    ],
    "Ghana": [
        "Greater Accra",
        "Kumasi (Ashanti)",
        "Tamale (Northern)",
        "Takoradi (Western)",
        "Cape Coast (Central)",
        "Sunyani (Bono)",
        "Ho (Volta)",
        "Koforidua (Eastern)",
        "Wa (Upper West)",
        "Bolgatanga (Upper East)",
    ],
    "South Africa": [
        "Johannesburg (Gauteng)",
        "Cape Town (Western Cape)",
        "Durban (KwaZulu-Natal)",
        "Pretoria (Tshwane)",
        "Port Elizabeth (Eastern Cape)",
        "Bloemfontein (Free State)",
        "Nelspruit (Mpumalanga)",
        "Polokwane (Limpopo)",
        "Kimberley (Northern Cape)",
        "Rustenburg (North West)",
    ],
    "Canada": [
        "Ontario (Toronto)",
        "British Columbia (Vancouver)",
        "Quebec (Montreal)",
        "Alberta (Calgary)",
        "Alberta (Edmonton)",
        "Manitoba (Winnipeg)",
        "Saskatchewan (Regina)",
        "Nova Scotia (Halifax)",
        "New Brunswick (Fredericton)",
        "Newfoundland (St. John's)",
    ],
    "India": [
        "Maharashtra (Mumbai)",
        "Karnataka (Bangalore)",
        "Delhi NCR",
        "Tamil Nadu (Chennai)",
        "Telangana (Hyderabad)",
        "West Bengal (Kolkata)",
        "Gujarat (Ahmedabad)",
        "Rajasthan (Jaipur)",
        "Punjab (Chandigarh)",
        "Uttar Pradesh (Lucknow)",
    ],
    "United Arab Emirates": [
        "Dubai",
        "Abu Dhabi",
        "Sharjah",
        "Ajman",
        "Ras Al Khaimah",
        "Fujairah",
        "Umm Al Quwain",
    ],
    "Germany": [
        "Berlin",
        "Munich (Bavaria)",
        "Hamburg",
        "Frankfurt (Hesse)",
        "Cologne (North Rhine-Westphalia)",
        "Stuttgart (Baden-Württemberg)",
        "Düsseldorf",
        "Leipzig (Saxony)",
        "Nuremberg",
        "Hannover (Lower Saxony)",
    ],
    "Egypt": [
        "Cairo",
        "Alexandria",
        "Giza",
        "Sharm El-Sheikh",
        "Luxor",
        "Aswan",
        "Port Said",
        "Suez",
        "Mansoura",
        "Tanta",
    ],
    "Rwanda": [
        "Kigali",
        "Musanze",
        "Huye",
        "Rubavu (Gisenyi)",
        "Muhanga",
    ],
    "Ethiopia": [
        "Addis Ababa",
        "Dire Dawa",
        "Mekelle",
        "Adama",
        "Hawassa",
    ],
    "Tanzania": [
        "Dar es Salaam",
        "Dodoma",
        "Zanzibar City",
        "Mwanza",
        "Arusha",
    ],
    "Senegal": [
        "Dakar",
        "Saint-Louis",
        "Thiès",
        "Ziguinchor",
        "Touba",
    ],
    "Côte d'Ivoire": [
        "Abidjan",
        "Bouaké",
        "Daloa",
        "Yamoussoukro",
        "San-Pédro",
    ],
    "France": [
        "Île-de-France (Paris)",
        "Auvergne-Rhône-Alpes (Lyon)",
        "Provence-Alpes-Côte d'Azur (Marseille)",
        "Occitanie (Toulouse)",
        "Nouvelle-Aquitaine (Bordeaux)",
        "Hauts-de-France (Lille)",
        "Grand Est (Strasbourg)",
        "Pays de la Loire (Nantes)",
        "Bretagne (Rennes)",
        "Normandie (Rouen)",
    ],
    "Singapore": [
        "Central Region",
        "East Region",
        "North Region",
        "North-East Region",
        "West Region",
    ],
    "Australia": [
        "New South Wales (Sydney)",
        "Victoria (Melbourne)",
        "Queensland (Brisbane)",
        "Western Australia (Perth)",
        "South Australia (Adelaide)",
        "Australian Capital Territory (Canberra)",
        "Tasmania (Hobart)",
        "Northern Territory (Darwin)",
    ],
    "Brazil": [
        "São Paulo",
        "Rio de Janeiro",
        "Minas Gerais (Belo Horizonte)",
        "Bahia (Salvador)",
        "Rio Grande do Sul (Porto Alegre)",
        "Paraná (Curitiba)",
        "Ceará (Fortaleza)",
        "Pernambuco (Recife)",
        "Amazonas (Manaus)",
        "Goiás (Goiânia)",
    ],
}


# ── Industries / Sectors ──────────────────────────────────────────────────────

INDUSTRIES: list[str] = [
    "Banking & Financial Services",
    "Fintech",
    "Real Estate & Property",
    "Healthcare & Pharmaceuticals",
    "Oil & Gas / Energy",
    "Telecommunications",
    "Logistics & Supply Chain",
    "Retail & E-Commerce",
    "Agriculture & Agribusiness",
    "Education & EdTech",
    "Insurance",
    "Manufacturing",
    "Media & Entertainment",
    "Construction & Infrastructure",
    "Information Technology (IT Services)",
    "Legal & Professional Services",
    "Hospitality & Tourism",
    "Non-Profit & NGOs",
    "Government & Public Sector",
    "Mining & Minerals",
]
